# allowable_values.py
"""
Canonical lists of allowable values for post-retrieval semantic filtering.
These are extracted from the actual database and represent all possible values.
"""

# All amenities available in the database
AMENITIES = [
    "assigned_parking",
    "balcony",
    "basement_finished",
    "basement_full",
    "basement_partial",
    "bike_room",
    "cats",
    "central_ac",
    "childrens_playroom",
    "city_view",
    "co_purchase",
    "cold_storage",
    "concierge",
    "courtyard",
    "deck",
    "decorative_fireplace",
    "dishwasher",
    "dogs",
    "doorman",
    "elevator",
    "fios_available",
    "fireplace",
    "full_time_doorman",
    "furnished",
    "garage",
    "garage_attached",
    "garden",
    "garden_view",
    "gas_fireplace",
    "gifts",
    "guarantors",
    "gym",
    "hardwood_floors",
    "hot_tub",
    "land_lease",
    "laundry",
    "leed_registered",
    "live_in_super",
    "locker_cage",
    "media_room",
    "nyc_evacuation_1",
    "nyc_evacuation_2",
    "nyc_evacuation_3",
    "nyc_evacuation_4",
    "nyc_evacuation_5",
    "nyc_evacuation_6",
    "package_room",
    "parents",
    "park_view",
    "parking",
    "part_time_doorman",
    "patio",
    "pets",
    "pied_a_terre",
    "pool",
    "private_roof_deck",
    "public_outdoor_space",
    "recreation_facilities",
    "roof_rights",
    "roofdeck",
    "skyline_view",
    "smoke_free",
    "storage",
    "storage_room",
    "sublets",
    "terrace",
    "valet",
    "valet_parking",
    "virtual_doorman",
    "washer_dryer",
    "waterfront",
    "waterview",
    "wheelchair_access",
    "wood_fireplace",
    "business_room",
    "guarantor_ok",
    "room_tennis"
]

# All neighborhoods in Manhattan
NEIGHBORHOODS = [
    "battery-park-city",
    "beekman",
    "carnegie-hill",
    "central-harlem",
    "chelsea",
    "chinatown",
    "east-harlem",
    "east-village",
    "financial-district",
    "flatiron",
    "fort-george",
    "fultonseaport",
    "gramercy-park",
    "greenwich-village",
    "hamilton-heights",
    "hells-kitchen",
    "hudson-heights",
    "hudson-square",
    "hudson-yards",
    "inwood",
    "kips-bay",
    "lenox-hill",
    "lincoln-square",
    "little-italy",
    "lower-east-side",
    "manhattan-valley",
    "manhattanville",
    "midtown",
    "midtown-south",
    "morningside-heights",
    "murray-hill",
    "noho",
    "nolita",
    "nomad",
    "roosevelt-island",
    "soho",
    "south-harlem",
    "stuyvesant-townpcv",
    "sutton-place",
    "tribeca",
    "turtle-bay",
    "two-bridges",
    "upper-carnegie-hill",
    "upper-east-side",
    "upper-west-side",
    "washington-heights",
    "west-chelsea",
    "west-harlem",
    "west-village",
    "yorkville",
    "central-park-south",
    "marble-hill"
]

# All subway routes
SUBWAY_ROUTES = [
    "1", "2", "3", "4", "5", "6", "7",
    "a", "b", "c", "d", "e", "f",
    "ferry",
    "j", "l", "lirr", "m", "n",
    "path",
    "q", "r", "s", "w", "z"
]

# All subway lines
SUBWAY_LINES = [
    "11 avenue",
    "2nd avenue",
    "63rd street",
    "6th avenue",
    "8th avenue",
    "broadway",
    "bway-7th ave",
    "canarsie",
    "clark street",
    "concourse",
    "ferry",
    "flushing",
    "lenox",
    "lexington",
    "nassau loop",
    "queens",
    "shuttle"
]

# Amenity synonyms for semantic matching
AMENITY_SYNONYMS = {
    "laundry": ["laundry", "washer_dryer", "washer dryer", "washer/dryer", "w/d", "in-unit laundry"],
    "washer_dryer": ["washer_dryer", "laundry", "washer dryer", "washer/dryer", "w/d", "in-unit laundry"],
    "doorman": ["doorman", "full_time_doorman", "part_time_doorman", "virtual_doorman", "attended lobby"],
    "parking": ["parking", "assigned_parking", "garage", "garage_attached", "valet_parking"],
    "gym": ["gym", "fitness", "fitness center", "recreation_facilities", "workout room"],
    "pool": ["pool", "swimming pool"],
    "elevator": ["elevator", "lift"],
    "storage": ["storage", "storage_room", "locker_cage", "cold_storage"],
    "outdoor_space": ["balcony", "terrace", "patio", "deck", "roofdeck", "private_roof_deck", "garden"],
    "pets": ["pets", "cats", "dogs", "pet friendly"],
    "fireplace": ["fireplace", "wood_fireplace", "gas_fireplace", "decorative_fireplace"],
    "view": ["city_view", "park_view", "waterview", "garden_view", "skyline_view"],
    "ac": ["central_ac", "air conditioning", "a/c"],
    "hardwood": ["hardwood_floors", "hardwood flooring"],
    "dishwasher": ["dishwasher"],
    "wheelchair_access": ["wheelchair_access", "accessible", "ada compliant"],
}

# Neighborhood aliases and common alternate names
NEIGHBORHOOD_ALIASES = {
    "financial district": ["financial-district", "fidi"],
    "fidi": ["financial-district"],
    "east village": ["east-village"],
    "west village": ["west-village"],
    "greenwich village": ["greenwich-village", "west-village", "the village"],
    "upper east side": ["upper-east-side", "ues"],
    "ues": ["upper-east-side"],
    "upper west side": ["upper-west-side", "uws"],
    "uws": ["upper-west-side"],
    "hells kitchen": ["hells-kitchen", "hell's kitchen", "clinton"],
    "midtown": ["midtown", "midtown-south"],
    "tribeca": ["tribeca", "triangle below canal"],
    "soho": ["soho", "south of houston"],
    "noho": ["noho", "north of houston"],
    "nolita": ["nolita", "north of little italy"],
    "nomad": ["nomad", "north of madison square park"],
    "flatiron": ["flatiron", "flatiron district"],
    "gramercy": ["gramercy-park", "gramercy"],
    "chelsea": ["chelsea", "west-chelsea"],
    "morningside heights": ["morningside-heights", "columbia area"],
    "harlem": ["central-harlem", "east-harlem", "west-harlem", "south-harlem"],
    "lower east side": ["lower-east-side", "les"],
    "les": ["lower-east-side"],
    "battery park": ["battery-park-city", "battery park"],
    "washington heights": ["washington-heights", "heights"],
    "inwood": ["inwood"],
}

