# Generated by Django 4.2.24 on 2025-10-15 16:34

import django.contrib.postgres.fields
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Building',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('building_id', models.CharField(db_index=True, max_length=50, unique=True)),
                ('address', models.CharField(max_length=255)),
                ('borough', models.CharField(db_index=True, max_length=50)),
                ('neighborhood', models.CharField(db_index=True, max_length=100)),
                ('zipcode', models.CharField(db_index=True, max_length=10)),
                ('latitude', models.DecimalField(blank=True, decimal_places=8, max_digits=10, null=True)),
                ('longitude', models.DecimalField(blank=True, decimal_places=8, max_digits=11, null=True)),
                ('built_in', models.IntegerField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'buildings',
            },
        ),
        migrations.CreateModel(
            name='Listing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('listing_id', models.CharField(db_index=True, max_length=50, unique=True)),
                ('status', models.CharField(choices=[('open', 'Open'), ('closed', 'Closed'), ('pending', 'Pending')], db_index=True, default='open', max_length=20)),
                ('listed_at', models.DateField()),
                ('closed_at', models.DateField(blank=True, null=True)),
                ('available_from', models.DateField(blank=True, null=True)),
                ('days_on_market', models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)])),
                ('address', models.CharField(db_index=True, max_length=255)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(0)])),
                ('borough', models.CharField(default='manhattan', max_length=50)),
                ('neighborhood', models.CharField(db_index=True, max_length=100)),
                ('zipcode', models.CharField(db_index=True, max_length=10)),
                ('property_type', models.CharField(choices=[('rental', 'Rental'), ('sale', 'Sale')], default='rental', max_length=20)),
                ('sqft', models.IntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0)])),
                ('bedrooms', models.IntegerField(db_index=True, validators=[django.core.validators.MinValueValidator(0)])),
                ('bathrooms', models.DecimalField(decimal_places=1, max_digits=3, validators=[django.core.validators.MinValueValidator(0)])),
                ('latitude', models.DecimalField(blank=True, decimal_places=8, max_digits=10, null=True)),
                ('longitude', models.DecimalField(blank=True, decimal_places=8, max_digits=11, null=True)),
                ('amenities', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=100), blank=True, default=list, size=None)),
                ('built_in', models.IntegerField(blank=True, null=True)),
                ('description', models.TextField(blank=True)),
                ('agents', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=200), blank=True, default=list, size=None)),
                ('no_fee', models.BooleanField(default=False)),
                ('images', django.contrib.postgres.fields.ArrayField(base_field=models.URLField(max_length=500), blank=True, default=list, size=None)),
                ('videos', django.contrib.postgres.fields.ArrayField(base_field=models.URLField(max_length=500), blank=True, default=list, size=None)),
                ('floorplans', django.contrib.postgres.fields.ArrayField(base_field=models.URLField(max_length=500), blank=True, default=list, size=None)),
                ('description_embedding', django.contrib.postgres.fields.ArrayField(base_field=models.FloatField(), blank=True, help_text='Vector embedding of the description for semantic search', null=True, size=None)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('building', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='listings', to='app.building')),
            ],
            options={
                'db_table': 'listings',
                'ordering': ['-listed_at', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='SubwayStation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('station_id', models.CharField(max_length=50, unique=True)),
                ('line', models.CharField(max_length=100)),
                ('routes', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=10), default=list, size=None)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'subway_stations',
            },
        ),
        migrations.CreateModel(
            name='ListingSubway',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('distance', models.DecimalField(decimal_places=2, help_text='Distance in miles', max_digits=5)),
                ('listing', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='nearby_subways', to='app.listing')),
                ('subway', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='nearby_listings', to='app.subwaystation')),
            ],
            options={
                'db_table': 'listing_subway',
                'ordering': ['distance'],
            },
        ),
        migrations.AddIndex(
            model_name='building',
            index=models.Index(fields=['neighborhood', 'zipcode'], name='buildings_neighbo_95cc02_idx'),
        ),
        migrations.AddIndex(
            model_name='building',
            index=models.Index(fields=['latitude', 'longitude'], name='buildings_latitud_21cd12_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='listingsubway',
            unique_together={('listing', 'subway')},
        ),
        migrations.AddIndex(
            model_name='listing',
            index=models.Index(fields=['status', 'price'], name='listings_status_8d0fb4_idx'),
        ),
        migrations.AddIndex(
            model_name='listing',
            index=models.Index(fields=['bedrooms', 'price'], name='listings_bedroom_36fec3_idx'),
        ),
        migrations.AddIndex(
            model_name='listing',
            index=models.Index(fields=['neighborhood', 'bedrooms', 'price'], name='listings_neighbo_9c47f2_idx'),
        ),
        migrations.AddIndex(
            model_name='listing',
            index=models.Index(fields=['listed_at'], name='listings_listed__a28689_idx'),
        ),
        migrations.AddIndex(
            model_name='listing',
            index=models.Index(fields=['days_on_market'], name='listings_days_on_91dbec_idx'),
        ),
    ]
